network.host: "0.0.0.0"
node.name: "node-1"
cluster.name: "wazuh-cluster"
cluster.initial_master_nodes:
  - "node-1"

node.max_local_storage_nodes: "3"
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.disabled: true

compatibility.override_main_response_version: true
